# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestForNetworking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitTestForNetworking
  pod 'Alamofire', '~> 5.5'

  target 'UnitTestForNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitTestForNetworkingUITests' do
    # Pods for testing
  end

end
